const screen = document.querySelector(".calculator--input")
const numberButtons = document.querySelectorAll(".calculator--number")
const add = document.querySelector("#add")
const sub = document.querySelector("#subtract")
const multi = document.querySelector("#multi")
const divider = document.querySelector("#divider")

const equal = document.querySelector("#equal")
const del = document.querySelector("#del")
const delAll = document.querySelector("#del-all")